[workspace]
authors = ["mark znidar <znidar.mark@gmail.com>"]
channels = ["pytorch", "nvidia", "pyg", "conda-forge"]
name = "GraphGPS"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
pytorch = {version = "1.13.*", channel = "pytorch"}
torchvision = {version = "*", channel = "pytorch"}
torchaudio = {version = "*", channel = "pytorch"}
pytorch-cuda = {version = "11.7.*", channel = "pytorch"}
pyg = {version = ">=2.2,<2.3", channel = "pyg"}
mkl = "2021.*"
setuptools = "<71"
scikit-learn = "<1.4"
openbabel = "*"
fsspec = "*"
rdkit = "*"

[pypi-dependencies]
networkx = "*"
pyg-lib = {url = "https://data.pyg.org/whl/torch-1.13.0+cu117/pyg_lib-0.3.1+pt113cu117-cp310-cp310-linux_x86_64.whl"}
pytorch-lightning = "*"
yacs = "*"
torchmetrics = "*"
performer-pytorch = "*"
tensorboardX = "*"
ogb = "*"
wandb = "*"
graphgps = {path = ".", editable = true}
